import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    tagline:       "Neural Document Intelligence",
    heroTitle:     ["Classify.", "Organize.", "Understand."],
    heroSub:       "Drop any folder of documents and let VisionVault automatically classify, extract, and organize them using AI — fully local or cloud-powered.",
    getStarted:    "Get Started",
    learnMore:     "Learn More",
    feat1:         "AI-Powered",
    feat2:         "100% Private",
    feat3:         "Lightning Fast",
    chooseMode:    "Choose Your Engine",
    chooseSub:     "Select how you want to power the analysis.",
    localMode:     "Local Model",
    localDesc:     "Run inference entirely on your machine. Private, offline, zero API costs.",
    cloudMode:     "Groq Cloud",
    cloudDesc:     "Blazing-fast cloud inference via Groq. Free API key required.",
    localBadge:    "OFFLINE",
    cloudBadge:    "CLOUD",
    localSetup:    "Local Model Setup",
    cloudSetup:    "Groq API Setup",
    onceOnly:      "One-time setup — saved locally, never shared.",
    modelPath:     "Model Path",
    modelPathPh:   "/models/llama-3.2-vision/gguf/...",
    apiKey:        "Groq API Key",
    apiKeyPh:      "gsk_••••••••••••••••••••••••",
    getGroqKey:    "Get your free Groq key at console.groq.com →",
    testConn:      "Test Connection",
    testing:       "Testing…",
    testOk:        "Connection successful ✓",
    testFail:      "Failed — check your key ✗",
    saveGo:        "Save & Continue →",
    settings:      "Settings",
    switchEngine:  "Switch Engine",
    dark:          "Dark",
    light:         "Light",
    back:          "Back",
    inputFolder:   "Input Folder",
    outputFolder:  "Output Folder",
    inputPh:       "/path/to/your/documents",
    outputPh:      "/path/to/output/archive",
    dropTitle:     "Drop folder or files here",
    dropSub:       "or click to browse",
    filesFound:    "files ready",
    startScan:     "Start Scan",
    analyzing:     "Analyzing documents…",
    processing:    "Processing",
    remaining:     "remaining",
    total:         "Total",
    processed:     "Processed",
    left:          "Remaining",
    done:          "Complete!",
    filesProcessed:"documents processed",
    successRate:   "Success rate",
    successLabel:  "Success",
    errorLabel:    "Errors",
    viewResults:   "Open Output Folder",
    scanAgain:     "New Scan",
    saved:         "Saved ✓",
  },
  fr: {
    tagline:       "Intelligence Documentaire Neurale",
    heroTitle:     ["Classifier.", "Organiser.", "Comprendre."],
    heroSub:       "Déposez un dossier de documents et laissez VisionVault les classifier, extraire et organiser automatiquement — en local ou via le cloud.",
    getStarted:    "Commencer",
    learnMore:     "En savoir plus",
    feat1:         "Propulsé par l'IA",
    feat2:         "100% Privé",
    feat3:         "Ultra Rapide",
    chooseMode:    "Choisissez votre moteur",
    chooseSub:     "Sélectionnez comment alimenter l'analyse.",
    localMode:     "Modèle Local",
    localDesc:     "Inférence entièrement sur votre machine. Privé, hors ligne, sans frais d'API.",
    cloudMode:     "Groq Cloud",
    cloudDesc:     "Inférence cloud ultra-rapide via Groq. Clé API gratuite requise.",
    localBadge:    "HORS LIGNE",
    cloudBadge:    "CLOUD",
    localSetup:    "Config. Modèle Local",
    cloudSetup:    "Config. API Groq",
    onceOnly:      "Configuration unique — sauvegardée localement, jamais partagée.",
    modelPath:     "Chemin du modèle",
    modelPathPh:   "/models/llama-3.2-vision/gguf/...",
    apiKey:        "Clé API Groq",
    apiKeyPh:      "gsk_••••••••••••••••••••••••",
    getGroqKey:    "Obtenez votre clé gratuite sur console.groq.com →",
    testConn:      "Tester la connexion",
    testing:       "Test en cours…",
    testOk:        "Connexion réussie ✓",
    testFail:      "Échec — vérifiez votre clé ✗",
    saveGo:        "Enregistrer et continuer →",
    settings:      "Paramètres",
    switchEngine:  "Changer de moteur",
    dark:          "Sombre",
    light:         "Clair",
    back:          "Retour",
    inputFolder:   "Dossier source",
    outputFolder:  "Dossier de destination",
    inputPh:       "/chemin/vers/vos/documents",
    outputPh:      "/chemin/vers/archive/sortie",
    dropTitle:     "Déposez un dossier ou des fichiers ici",
    dropSub:       "ou cliquez pour parcourir",
    filesFound:    "fichiers prêts",
    startScan:     "Lancer le scan",
    analyzing:     "Analyse des documents…",
    processing:    "Traitement",
    remaining:     "restant",
    total:         "Total",
    processed:     "Traités",
    left:          "Restants",
    done:          "Terminé !",
    filesProcessed:"documents traités",
    successRate:   "Taux de succès",
    successLabel:  "Succès",
    errorLabel:    "Erreurs",
    viewResults:   "Ouvrir le dossier de sortie",
    scanAgain:     "Nouveau scan",
    saved:         "Enregistré ✓",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = translations[lang];
  const toggle = () => setLang(l => l === "en" ? "fr" : "en");
  return (
    <LangContext.Provider value={{ t, lang, toggle, setLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
